### PR TITLE
Added support to generate Google Image Sitemaps

### PR DESCRIPTION
**Pull request by adammahmood**

### CODE REVIEW

**Comment by vinicius73** [comment]
+1

**Comment by ivank** [comment]
+1

**Comment by ThePixelDeveloper** [comment]
Sorry I've taken so long to notice this, looks like I'm not getting notified of activity on my project. Will take a look over this and hopefully get it in the new release later this week.

**Comment by ThePixelDeveloper** [comment]
Worked on this on the v4 line, https://github.com/ThePixelDeveloper/Sitemap-v2/tree/develop Going to make a few cleanups and merge it in soon.

**Pull request closed without merging**
